temperature: 0
max_tokens: 0
max_context_window: 200000
base_url: https://openrouter.ai/api/v1
api_key: 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
models:
- openai/openai/gpt-4o